RD /S/Q "Chat Server\obj\debug"
RD /S/Q "Chat Server\obj\release"
RD /S/Q "Chat Server\bin\debug"
RD /S/Q "Chat Server\bin\release"
RD /S/Q "Chat Client\obj\debug"
RD /S/Q "Chat Client\obj\release"
RD /S/Q "Chat Client\bin\debug"
RD /S/Q "Chat Client\bin\release"
RD /S/Q "RemoteObject\obj\debug"
RD /S/Q "RemoteObject\obj\release"
RD /S/Q "RemoteObject\bin\debug"
RD /S/Q "RemoteObject\bin\release"